@echo off
echo This batch file uninstalls the DLLs required to use MPXJ from the GAC
pause
gacutil /u IKVM.AWT.WinForms
gacutil /u IKVM.OpenJDK.Beans
gacutil /u IKVM.OpenJDK.Charsets
gacutil /u IKVM.OpenJDK.Cldrdata
gacutil /u IKVM.OpenJDK.Corba
gacutil /u IKVM.OpenJDK.Core
gacutil /u IKVM.OpenJDK.Jdbc
gacutil /u IKVM.OpenJDK.Localedata
gacutil /u IKVM.OpenJDK.Management
gacutil /u IKVM.OpenJDK.Media
gacutil /u IKVM.OpenJDK.Misc
gacutil /u IKVM.OpenJDK.Naming
gacutil /u IKVM.OpenJDK.Nashorn
gacutil /u IKVM.OpenJDK.Remoting
gacutil /u IKVM.OpenJDK.Security
gacutil /u IKVM.OpenJDK.SwingAWT
gacutil /u IKVM.OpenJDK.Text
gacutil /u IKVM.OpenJDK.Tools
gacutil /u IKVM.OpenJDK.Util
gacutil /u IKVM.OpenJDK.XML.API
gacutil /u IKVM.OpenJDK.XML.Bind
gacutil /u IKVM.OpenJDK.XML.Crypto
gacutil /u IKVM.OpenJDK.XML.Parse
gacutil /u IKVM.OpenJDK.XML.Transform
gacutil /u IKVM.OpenJDK.XML.WebServices
gacutil /u IKVM.OpenJDK.XML.XPath
gacutil /u IKVM.Reflection
gacutil /u IKVM.Runtime.JNI
gacutil /u IKVM.Runtime
gacutil /u commons-collections4-4.4
gacutil /u commons-io-2.11.0
gacutil /u commons-lang3-3.10
gacutil /u commons-logging-1.2
gacutil /u commons-math3-3.6.1
gacutil /u ikvm-native-win32-x64
gacutil /u ikvm-native-win32-x86
gacutil /u jackcess-4.0.1
gacutil /u jsoup-1.15.3
gacutil /u junit
gacutil /u log4j-api-2.17.2
gacutil /u mpxj-for-csharp
gacutil /u mpxj-for-vb
gacutil /u mpxj-test
gacutil /u mpxj
gacutil /u poi-5.2.2
gacutil /u rtfparserkit-1.16.0
gacutil /u sqlite-jdbc-3.42.0.0
